server:
  port: 8081

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: user-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://consort-postgres:5432/${POSTGRES_DB:consort_group}}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: consort-redis-user-service
      port: 6379

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  # === Kafka ===
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:forum-service-group}
      auto-offset-reset: latest
      properties:
        session.timeout.ms: ${SPRING_KAFKA_CONSUMER_SESSION_TIMEOUT_MS:10000}
        heartbeat.interval.ms: ${SPRING_KAFKA_CONSUMER_HEARTBEAT_INTERVAL_MS:3000}
        max.partition.fetch.bytes: ${SPRING_KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES:1048576}
      max-poll-records: ${SPRING_KAFKA_CONSUMER_MAX_POLL_RECORDS:500}
      max-poll-interval: ${SPRING_KAFKA_CONSUMER_MAX_POLL_INTERVAL_MS:300000}
    producer:
      acks: all
      retries: 10
    admin:
      auto-create: true

logging:
  level:
    root: INFO
    org.springframework: DEBUG

# === Бизнесовые топики ===
topics:
  user-registration: user-registered-topic
  user-update-profile: user-update-profile-topic
  verification-code-resent: verification-code-resent-topic
  password-reset-request: password-reset-request-topic
  super-admin-action: super-admin-action-topic
  mentor-action: mentor-action-topic
  course-group: course-group-opened-topic
  course-purchased: course-purchased-topic
  course-forum-group: course-forum-group-created-topic
  hr-action: hr-action-topic

app:
  link: http://consort-user-service:8081/index.html

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8762/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

oneid:
  base-url: https://sso.egov.uz/sso/oauth/Authorization.do
  client-id: CLIENT_ID
  client-secret: CLIENT_SECRET
  redirect-uri: http://api-gateway-service:8085/api/v1/oneid/callback
  token-url: https://sso.egov.uz/sso/oauth/Token.do
  profile-url: https://sso.egov.uz/sso/oauth/userinfo
  time-out: 5000

mintrud:
  api:
    token: wUIBjx3G1C1Ee+eIXtt/zVIFkS40lhoan0
    url: https://example.com/mintrud/api

security:
  token: ${SECURITY_TOKEN}
  expiration: 3600000

async:
  core-pool-size: 5
  max-pool-size: 10
  queue-capacity: 15
  thread-name-prefix: user-service

cache:
  redis-batch-size: 500

course:
  service:
    url: http://consort-course-service:8084

payment:
  service:
    url: http://consort-payment-service:8086

notification:
  service:
    url: http://consort-notification-service:8082

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    docExpansion: full
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 3
    defaultModelRendering: schema
    operationsSorter: method
    tagsSorter: alpha
  model-converters:
    pageable-converter:
      enabled: true
