server:
  port: 8081
  forward-headers-strategy: framework

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: user-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:consort-postgres}:${DB_PORT:5432}/${POSTGRES_DB:consort_group}}
    username: ${DB_USERNAME:${POSTGRES_USER:consort}}
    password: ${DB_PASSWORD:${POSTGRES_PASSWORD:consort}}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: ${REDIS_USER_HOST:consort-redis-user-service}
      port: ${REDIS_USER_PORT:6379}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
        shutdown-timeout: 100ms

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:"consort-kafka:9092"}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:user-service-group}
      auto-offset-reset: latest
      max-poll-records: ${SPRING_KAFKA_CONSUMER_MAX_POLL_RECORDS:500}
      properties:
        session.timeout.ms: ${SPRING_KAFKA_CONSUMER_SESSION_TIMEOUT_MS:10000}
        heartbeat.interval.ms: ${SPRING_KAFKA_CONSUMER_HEARTBEAT_INTERVAL_MS:3000}
        max.partition.fetch.bytes: ${SPRING_KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES:1048576}
        max.poll.interval.ms: ${SPRING_KAFKA_CONSUMER_MAX_POLL_INTERVAL_MS:300000}
    producer:
      acks: all
      retries: 10
    properties:
      metadata.max.age.ms: 30000

logging:
  level:
    root: INFO
    org.springframework: DEBUG

# Бизнес-топики
kafka:
  user-registration: user-registered-topic
  user-update-profile: user-update-profile-topic
  verification-code-resent: verification-code-resent-topic
  password-reset-request: password-reset-request-topic
  super-admin-action: super-admin-action-topic
  mentor-action: mentor-action-topic
  course-group: course-group-opened-topic
  course-purchased: course-purchased-topic
  course-forum-group: course-forum-group-created-topic
  hr-action: hr-action-topic

app:
  link: ${APP_LINK:http://consort-user-service:8081/index.html}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://consort-eureka-service:8762/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${HOSTNAME}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
      show-components: when_authorized
  health:
    redis:
      enabled: false
    db:
      enabled: true
    defaults:
      enabled: true
    diskspace:
      enabled: true
    ping:
      enabled: true

oneid:
  base-url: https://sso.egov.uz/sso/oauth/Authorization.do
  client-id: ${ONEID_CLIENT_ID:CLIENT_ID}
  client-secret: ${ONEID_CLIENT_SECRET:CLIENT_SECRET}
  redirect-uri: ${ONEID_REDIRECT_URI:http://api-gateway-service:8085/api/v1/oneid/callback}
  token-url: https://sso.egov.uz/sso/oauth/Token.do
  profile-url: https://sso.egov.uz/sso/oauth/userinfo
  time-out: 5000

mintrud:
  api:
    token: ${MINTRUD_TOKEN:wUIBjx3G1C1Ee+eIXtt/zVIFkS40lhoan0}
    url: ${MINTRUD_URL:https://example.com/mintrud/api}

security:
  token: ${SECURITY_TOKEN}
  expiration: ${JWT_EXPIRATION_MS:3600000}

async:
  core-pool-size: 5
  max-pool-size: 10
  queue-capacity: 15
  thread-name-prefix: user-service

cache:
  redis-batch-size: 500

course:
  service:
    url: ${COURSE_SERVICE_URL:http://consort-course-service:8084}

payment:
  service:
    url: ${PAYMENT_SERVICE_URL:http://consort-payment-service:8086}

notification:
  service:
    url: ${NOTIFICATION_SERVICE_URL:http://consort-notification-service:8082}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    docExpansion: full
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 3
    defaultModelRendering: schema
    operationsSorter: method
    tagsSorter: alpha
    use-root-path: true
  model-converters:
    pageable-converter:
      enabled: true
