CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS user_schema.users (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    language VARCHAR(20) NOT NULL,
    last_name VARCHAR(50) DEFAULT NULL,
    first_name VARCHAR(50) DEFAULT NULL,
    middle_name VARCHAR(50) DEFAULT NULL,
    born_date DATE DEFAULT NULL,
    phone_number VARCHAR(13) DEFAULT NULL UNIQUE,
    work_place VARCHAR(128) DEFAULT NULL,
    email VARCHAR(128) NOT NULL UNIQUE,
    position VARCHAR(128) DEFAULT NULL,
    pinfl VARCHAR(16) DEFAULT NULL UNIQUE,
    oneid_user_id VARCHAR(128) DEFAULT NULL UNIQUE,
    oneid_access_token VARCHAR(512) DEFAULT NULL,
    oneid_refresh_token VARCHAR(512) DEFAULT NULL,
    oneid_access_expires_at TIMESTAMP DEFAULT NULL,
    oneid_token_issued_at TIMESTAMP DEFAULT NULL,
    oneid_token_updated_at TIMESTAMP DEFAULT NULL,
    mehnat_data_fetched BOOLEAN DEFAULT FALSE,
    mehnat_position_start_date DATE DEFAULT NULL,
    mehnat_organization_tin VARCHAR(50) DEFAULT NULL,
    mehnat_department_name VARCHAR(128) DEFAULT NULL,
    is_verified BOOLEAN DEFAULT FALSE,
    role VARCHAR(50) DEFAULT NULL,
    status VARCHAR(50) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT NULL,
    last_login TIMESTAMP DEFAULT NULL
);
