CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS user_schema.users (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    language VARCHAR(20) NOT NULL,
    last_name VARCHAR(50) DEFAULT NULL,
    first_name VARCHAR(50) DEFAULT NULL,
    middle_name VARCHAR(50) DEFAULT NULL,
    born_date DATE DEFAULT NULL,
    phone_number VARCHAR(13) DEFAULT NULL UNIQUE,
    work_place VARCHAR(128) DEFAULT NULL,
    email VARCHAR(128) NOT NULL UNIQUE,
    position VARCHAR(128) DEFAULT NULL,
    pinfl VARCHAR(16) DEFAULT NULL UNIQUE,
    is_verified BOOLEAN DEFAULT FALSE,
    role VARCHAR(50) DEFAULT NULL,
    status VARCHAR(50) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT NULL,
    last_login TIMESTAMP DEFAULT NULL
);
